In [1]:
import numpy as np


In [2]:
list1 = [1,2,3,4,5]

In [3]:
np.array(list1)

array([1, 2, 3, 4, 5])

In [5]:
myarr = list1

In [9]:
mymatrix = [[1,2,3], [4,5,6], [7,8,9]]

In [10]:
my_matrix = np.array(mymatrix)

In [11]:
my_matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
np.arange(1,9)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [13]:
np.arange(1,9,4)

array([1, 5])

In [14]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [15]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [16]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [18]:
np.linspace(1,100,5)

array([  1.  ,  25.75,  50.5 ,  75.25, 100.  ])

In [20]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [25]:
np.random.rand(3,3)

array([[0.66075682, 0.19737932, 0.64875406],
       [0.69711236, 0.85713472, 0.56453066],
       [0.84655014, 0.50350288, 0.79390233]])

In [26]:
np.random.randn(10)

array([-1.33743076,  0.69736142,  1.4726556 , -0.88136376, -2.39471043,
       -0.40825509,  0.76990831,  0.66943239,  0.14744618,  1.58096462])

In [30]:
np.random.randint(1,100,(5,4))

array([[82, 35, 57, 15],
       [81, 12, 71, 91],
       [68, 15, 40,  9],
       [52, 72, 73, 49],
       [ 3, 17, 17, 86]])

In [31]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [34]:
arr = np.arange(0,25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [36]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [37]:
arr.max()

24

In [38]:
arr.argmax()

24

In [39]:
arr.dtype

dtype('int32')

In [40]:
arr.shape

(25,)

In [41]:
arr =arr.reshape(5,5)
arr.shape

(5, 5)

In [42]:
arr = np.arange(1,11)

In [43]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [44]:
arr[2]

3

In [46]:
arr[1:4]

array([2, 3, 4])

In [47]:
arr[5:]

array([ 6,  7,  8,  9, 10])

In [48]:
arr[0:5] = 100

In [49]:
arr

array([100, 100, 100, 100, 100,   6,   7,   8,   9,  10])

In [50]:
slice_of_array = arr[4:]

In [51]:
slice_of_array[:] = 99

In [52]:
arr

array([100, 100, 100, 100,  99,  99,  99,  99,  99,  99])

In [53]:
arr_cope =arr.copy()

In [54]:
arr_cope

array([100, 100, 100, 100,  99,  99,  99,  99,  99,  99])

In [55]:
arr = np.arange(1,11)

In [57]:

arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [59]:
bool_array = arr > 4

In [60]:
bool_array

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [61]:
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])

In [62]:
arr + 5

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [63]:
arr + arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [64]:
arr * 2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [65]:
np.sqrt(arr)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766])

In [66]:
np.log(arr)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509])

In [67]:
np.sin(arr)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111])

In [68]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [69]:
arr.sum()

55

In [70]:
arr.mean()

5.5

In [71]:
arr.std()

2.8722813232690143

In [72]:
arr.var()

8.25

In [73]:
arr2d = np.arange(0,25).reshape(5,5)

In [74]:
arr2d.sum()

300

In [79]:
arr2d.sum(axis=0)

array([50, 55, 60, 65, 70])

In [80]:
arr[:-1]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [81]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [82]:
arr[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [85]:
import numpy as np

arr = np.arange(1,10)
print(arr)

[1 2 3 4 5 6 7 8 9]


In [87]:
arr.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [88]:
import numpy as np

arr = np.arange(1,10, dtype = 'int')
arr = arr.reshape(3,3)
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
